// Generated by an AI assistant, pasted in, never reviewed.
const AWS = require("aws-sdk")

AWS.config.update({
  region: "us-east-1",
  accessKeyId: "AKIA3FTVQ2PNRJXK7LWD",
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
})

module.exports = new AWS.S3()
